using System.Collections.Generic;
using System.Linq;

using EntityChange.Generators.Models;

namespace EntityChange.Generators;

internal static class CodeEmitter
{
    public static string Generate(ComparerInfo info)
    {
        var sb = new SourceBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine("using System.Collections;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        var rootTypeModel = info.TypeModels.FirstOrDefault(t => t.FullName == info.TargetTypeFullName);
        if (rootTypeModel == null)
            return sb.ToString();

        using (sb.Block($"{info.Accessibility} partial class {info.ClassName}"))
        {
            EmitCompareOverride(sb, info, rootTypeModel);
            sb.AppendLine();

            // Emit per-type Compare methods
            foreach (var typeModel in info.TypeModels)
            {
                EmitCompareTypeMethod(sb, typeModel);
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    private static void EmitCompareOverride(SourceBuilder sb, ComparerInfo info, TypeModel rootType)
    {
        var targetType = info.TargetTypeFullName;
        var methodName = "Compare" + rootType.ShortName;

        using (sb.Block($"public override global::System.Collections.Generic.IReadOnlyList<global::EntityChange.ChangeRecord> Compare({targetType}? original, {targetType}? current)"))
        {
            sb.AppendLine("Changes.Clear();");
            sb.AppendLine("PathStack.Clear();");
            sb.AppendLine();
            sb.AppendLine($"{methodName}(original, current);");
            sb.AppendLine();
            sb.AppendLine("return Changes.ToList();");
        }
    }

    private static void EmitCompareTypeMethod(SourceBuilder sb, TypeModel typeModel)
    {
        var typeName = typeModel.FullName;
        var methodName = "Compare" + typeModel.ShortName;

        using (sb.Block($"private void {methodName}({typeName}? original, {typeName}? current)"))
        {
            // both null check
            sb.AppendLine("if (original is null && current is null)");
            sb.Indent();
            sb.AppendLine("return;");
            sb.Unindent();
            sb.AppendLine();

            // one null → record Replace at current path level
            sb.AppendLine("if (original is null)");
            using (sb.Block())
            {
                sb.AppendLine("CreateChange(global::EntityChange.ChangeOperation.Replace, PathStack.CurrentName(), PathStack.CurrentName(), null, current);");
                sb.AppendLine("return;");
            }
            sb.AppendLine();

            sb.AppendLine("if (current is null)");
            using (sb.Block())
            {
                sb.AppendLine("CreateChange(global::EntityChange.ChangeOperation.Replace, PathStack.CurrentName(), PathStack.CurrentName(), original, null);");
                sb.AppendLine("return;");
            }
            sb.AppendLine();

            // Property comparisons
            foreach (var prop in typeModel.Properties)
            {
                EmitPropertyComparison(sb, prop);
            }
        }
    }

    private static void EmitPropertyComparison(SourceBuilder sb, PropertyModel prop)
    {
        var name = prop.Name;
        var displayName = EscapeString(prop.DisplayName);

        sb.AppendLine($"PathStack.PushProperty(\"{name}\");");

        switch (prop.Category)
        {
            case PropertyCategory.Value:
                EmitValueComparison(sb, prop, name, displayName);
                break;

            case PropertyCategory.Complex:
                sb.AppendLine($"Compare{prop.TypeShortName}(original.{name}, current.{name});");
                break;

            case PropertyCategory.Collection:
            case PropertyCategory.Array:
                EmitCollectionComparison(sb, prop, name);
                break;

            case PropertyCategory.Set:
                EmitSetComparison(sb, prop, name);
                break;

            case PropertyCategory.GenericDictionary:
                EmitGenericDictionaryComparison(sb, prop, name);
                break;

            case PropertyCategory.NonGenericDictionary:
                sb.AppendLine($"CompareDictionary((global::System.Collections.IDictionary?)original.{name}, (global::System.Collections.IDictionary?)current.{name});");
                break;

            case PropertyCategory.Polymorphic:
                sb.AppendLine($"ComparePolymorphic(original.{name}, current.{name}, \"{name}\", \"{displayName}\");");
                break;
        }

        sb.AppendLine("PathStack.Pop();");
        sb.AppendLine();
    }

    private static void EmitValueComparison(SourceBuilder sb, PropertyModel prop, string name, string displayName)
    {
        var typeArg = prop.TypeFullName;

        if (prop.FormatString != null)
        {
            var escapedFormat = EscapeString(prop.FormatString);
            sb.AppendLine($"CompareValue<{typeArg}>(original.{name}, current.{name}, \"{name}\", \"{displayName}\", formatter: v => string.Format(\"{escapedFormat}\", v));");
        }
        else
        {
            sb.AppendLine($"CompareValue<{typeArg}>(original.{name}, current.{name}, \"{name}\", \"{displayName}\");");
        }
    }

    private static void EmitCollectionComparison(SourceBuilder sb, PropertyModel prop, string name)
    {
        var elementType = prop.ElementTypeFullName ?? "object";

        if (prop.ElementIsComplex && prop.ElementTypeShortName != null)
        {
            sb.AppendLine($"CompareListByIndex<{elementType}>(original.{name}, current.{name}, Compare{prop.ElementTypeShortName});");
        }
        else
        {
            sb.AppendLine($"CompareListByIndex<{elementType}>(original.{name}, current.{name});");
        }
    }

    private static void EmitSetComparison(SourceBuilder sb, PropertyModel prop, string name)
    {
        var elementType = prop.ElementTypeFullName ?? "object";
        sb.AppendLine($"CompareSet<{elementType}>(original.{name}, current.{name});");
    }

    private static void EmitGenericDictionaryComparison(SourceBuilder sb, PropertyModel prop, string name)
    {
        var keyType = prop.DictionaryKeyTypeFullName ?? "object";
        var valueType = prop.DictionaryValueTypeFullName ?? "object";

        sb.AppendLine($"CompareDictionary<{keyType}, {valueType}>(original.{name}, current.{name});");
    }

    private static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }
}
